name: workshop
channels:
  - anaconda
  - conda-forge
dependencies:
  - python=3.9.4
  - jupyter
  - pandas
  - matplotlib
  - spyder=4.2.0
  - jupyter
  - numpy
  - markupsafe==2.0.1
# - pyreadline 
# uncomment pyreadline only if installing on conda for windows
